# TCL File Generated by Component Editor 19.1
# Wed Jun 03 17:13:23 CDT 2020
# DO NOT MODIFY


# 
# avalon_microphone_system "avalon_microphone_system" v1.0
# JJ 2020.06.03.17:13:23
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_microphone_system
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_microphone_system
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Augmented Listening Project"
set_module_property AUTHOR JJ
set_module_property DISPLAY_NAME avalon_microphone_system
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_microphone_system
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_microphone_system.sv SYSTEM_VERILOG PATH avalon_microphone_system.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock CLK
set_interface_property avalon_master associatedReset RST
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master AM_ADDR address Output 32
add_interface_port avalon_master AM_BURSTCOUNT burstcount Output 3
add_interface_port avalon_master AM_WRITE write Output 1
add_interface_port avalon_master AM_WRITEDATA writedata Output 32
add_interface_port avalon_master AM_BYTEENABLE byteenable Output 4
add_interface_port avalon_master AM_WAITREQUEST waitrequest Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock CLK
set_interface_property avalon_slave associatedReset RST
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave AVL_READ read Input 1
add_interface_port avalon_slave AVL_WRITE write Input 1
add_interface_port avalon_slave AVL_CS chipselect Input 1
add_interface_port avalon_slave AVL_ADDR address Input 3
add_interface_port avalon_slave AVL_WRITEDATA writedata Input 32
add_interface_port avalon_slave AVL_READDATA readdata Output 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point i2s_bclk
# 
add_interface i2s_bclk clock end
set_interface_property i2s_bclk clockRate 0
set_interface_property i2s_bclk ENABLED true
set_interface_property i2s_bclk EXPORT_OF ""
set_interface_property i2s_bclk PORT_NAME_MAP ""
set_interface_property i2s_bclk CMSIS_SVD_VARIABLES ""
set_interface_property i2s_bclk SVD_ADDRESS_GROUP ""

add_interface_port i2s_bclk AUD_BCLK clk Input 1


# 
# connection point i2s_lrclk
# 
add_interface i2s_lrclk clock end
set_interface_property i2s_lrclk clockRate 0
set_interface_property i2s_lrclk ENABLED true
set_interface_property i2s_lrclk EXPORT_OF ""
set_interface_property i2s_lrclk PORT_NAME_MAP ""
set_interface_property i2s_lrclk CMSIS_SVD_VARIABLES ""
set_interface_property i2s_lrclk SVD_ADDRESS_GROUP ""

add_interface_port i2s_lrclk AUD_ADCLRCK clk Input 1


# 
# connection point GPIO_DIN1
# 
add_interface GPIO_DIN1 conduit end
set_interface_property GPIO_DIN1 associatedClock i2s_bclk
set_interface_property GPIO_DIN1 associatedReset ""
set_interface_property GPIO_DIN1 ENABLED true
set_interface_property GPIO_DIN1 EXPORT_OF ""
set_interface_property GPIO_DIN1 PORT_NAME_MAP ""
set_interface_property GPIO_DIN1 CMSIS_SVD_VARIABLES ""
set_interface_property GPIO_DIN1 SVD_ADDRESS_GROUP ""

add_interface_port GPIO_DIN1 GPIO_DIN1 new_signal Input 1


# 
# connection point GPIO_DIN2
# 
add_interface GPIO_DIN2 conduit end
set_interface_property GPIO_DIN2 associatedClock i2s_bclk
set_interface_property GPIO_DIN2 associatedReset ""
set_interface_property GPIO_DIN2 ENABLED true
set_interface_property GPIO_DIN2 EXPORT_OF ""
set_interface_property GPIO_DIN2 PORT_NAME_MAP ""
set_interface_property GPIO_DIN2 CMSIS_SVD_VARIABLES ""
set_interface_property GPIO_DIN2 SVD_ADDRESS_GROUP ""

add_interface_port GPIO_DIN2 GPIO_DIN2 new_signal Input 1


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 50000000
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK clk Input 1


# 
# connection point GPIO_DIN3
# 
add_interface GPIO_DIN3 conduit end
set_interface_property GPIO_DIN3 associatedClock i2s_bclk
set_interface_property GPIO_DIN3 associatedReset ""
set_interface_property GPIO_DIN3 ENABLED true
set_interface_property GPIO_DIN3 EXPORT_OF ""
set_interface_property GPIO_DIN3 PORT_NAME_MAP ""
set_interface_property GPIO_DIN3 CMSIS_SVD_VARIABLES ""
set_interface_property GPIO_DIN3 SVD_ADDRESS_GROUP ""

add_interface_port GPIO_DIN3 GPIO_DIN3 new_signal Input 1


# 
# connection point GPIO_DIN4
# 
add_interface GPIO_DIN4 conduit end
set_interface_property GPIO_DIN4 associatedClock i2s_bclk
set_interface_property GPIO_DIN4 associatedReset ""
set_interface_property GPIO_DIN4 ENABLED true
set_interface_property GPIO_DIN4 EXPORT_OF ""
set_interface_property GPIO_DIN4 PORT_NAME_MAP ""
set_interface_property GPIO_DIN4 CMSIS_SVD_VARIABLES ""
set_interface_property GPIO_DIN4 SVD_ADDRESS_GROUP ""

add_interface_port GPIO_DIN4 GPIO_DIN4 new_signal Input 1


# 
# connection point RST
# 
add_interface RST reset end
set_interface_property RST associatedClock i2s_bclk
set_interface_property RST synchronousEdges DEASSERT
set_interface_property RST ENABLED true
set_interface_property RST EXPORT_OF ""
set_interface_property RST PORT_NAME_MAP ""
set_interface_property RST CMSIS_SVD_VARIABLES ""
set_interface_property RST SVD_ADDRESS_GROUP ""

add_interface_port RST RESET reset Input 1

