# TCL File Generated by Component Editor 19.1
# Mon Jun 01 12:59:28 CDT 2020
# DO NOT MODIFY


# 
# avalon_microphone_interface "avalon_microphone_interface" v1.0
#  2020.06.01.12:59:28
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_microphone_interface
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_microphone_interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Augmented Listening Project"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_microphone_interface
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_microphone_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_microphone_interface.sv SYSTEM_VERILOG PATH avalon_microphone_interface.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock CLK
set_interface_property avalon_slave associatedReset RST
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave AVL_ADDR address Input 3
add_interface_port avalon_slave AVL_READ read Input 1
add_interface_port avalon_slave AVL_WRITE write Input 1
add_interface_port avalon_slave AVL_CS chipselect Input 1
add_interface_port avalon_slave AVL_WRITEDATA writedata Input 32
add_interface_port avalon_slave AVL_READDATA readdata Output 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 0
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK clk Input 1


# 
# connection point RST
# 
add_interface RST reset end
set_interface_property RST associatedClock CLK
set_interface_property RST synchronousEdges DEASSERT
set_interface_property RST ENABLED true
set_interface_property RST EXPORT_OF ""
set_interface_property RST PORT_NAME_MAP ""
set_interface_property RST CMSIS_SVD_VARIABLES ""
set_interface_property RST SVD_ADDRESS_GROUP ""

add_interface_port RST RST reset Input 1


# 
# connection point sd
# 
add_interface sd conduit end
set_interface_property sd associatedClock CLK
set_interface_property sd associatedReset ""
set_interface_property sd ENABLED true
set_interface_property sd EXPORT_OF ""
set_interface_property sd PORT_NAME_MAP ""
set_interface_property sd CMSIS_SVD_VARIABLES ""
set_interface_property sd SVD_ADDRESS_GROUP ""

add_interface_port sd sd new_signal Input 1


# 
# connection point sck
# 
add_interface sck clock end
set_interface_property sck clockRate 0
set_interface_property sck ENABLED true
set_interface_property sck EXPORT_OF ""
set_interface_property sck PORT_NAME_MAP ""
set_interface_property sck CMSIS_SVD_VARIABLES ""
set_interface_property sck SVD_ADDRESS_GROUP ""

add_interface_port sck sck clk Input 1


# 
# connection point ws
# 
add_interface ws clock end
set_interface_property ws clockRate 0
set_interface_property ws ENABLED true
set_interface_property ws EXPORT_OF ""
set_interface_property ws PORT_NAME_MAP ""
set_interface_property ws CMSIS_SVD_VARIABLES ""
set_interface_property ws SVD_ADDRESS_GROUP ""

add_interface_port ws ws clk Input 1

